app:
    env: development
    debug: True
    server:
        port: 8050

database:
    dialect: postgresql
    driver: psycopg2
    hostname: localhost
    db_name: weather_db
    username: weatherman
    password: WonkF4RY
    db_schema: public
    port: 5432

dashboards: [rfms, gwms, tdms]
